-- +goose Up
-- +goose StatementBegin
ALTER TABLE public.conferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.divisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leagues ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.individuals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.individual_statuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rosters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.games ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.game_statuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.entity_vendor_ids ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nba_box_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nba_markets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nba_plays ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nba_play_statistics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nfl_box_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nfl_markets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nfl_drives ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nfl_plays ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nfl_play_statistics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.odds_blaze_market_ids ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.odds_blaze_market_outcomes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.goose_db_version ENABLE ROW LEVEL SECURITY;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
ALTER TABLE public.conferences DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.divisions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.leagues DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sports DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.teams DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.individuals DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.individual_statuses DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.rosters DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.games DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.game_statuses DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.entity_vendor_ids DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.nba_box_scores DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.nba_markets DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.nba_plays DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.nba_play_statistics DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.nfl_box_scores DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.nfl_markets DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.nfl_drives DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.nfl_plays DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.nfl_play_statistics DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.odds_blaze_market_ids DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.odds_blaze_market_outcomes DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.goose_db_version DISABLE ROW LEVEL SECURITY;
-- +goose StatementEnd
