-- +goose Up
-- +goose StatementBegin

-- =============================================================================
-- Remove market_type from exchange_slates
-- Market IDs are UUIDs generated by gen_random_uuid() in nba_markets and
-- nfl_markets, so they are globally unique. The market type can always be
-- derived via resolve_market_entity_type(). Removing the column allows slates
-- to contain markets from multiple sports.
-- =============================================================================

-- Drop the old unique constraint that included market_type
ALTER TABLE exchange_slates
    DROP CONSTRAINT exchange_slates_market_type_market_ids_unique;

-- Drop the market_type column
ALTER TABLE exchange_slates
    DROP COLUMN market_type;

-- Add a new unique constraint on just market_ids
ALTER TABLE exchange_slates
    ADD CONSTRAINT exchange_slates_market_ids_unique UNIQUE (market_ids);

-- =============================================================================
-- Replace validate_market_ids to no longer require a market_type parameter.
-- Validates that every market ID exists in at least one market table.
-- =============================================================================
DROP FUNCTION validate_market_ids(market_entity_type, UUID[]);

CREATE FUNCTION validate_market_ids(
    p_market_ids UUID[]
) RETURNS VOID AS $$
DECLARE
    v_missing UUID[];
BEGIN
    SELECT ARRAY(
        SELECT unnest(p_market_ids)
        EXCEPT
        (
            SELECT id FROM nba_markets WHERE id = ANY(p_market_ids)
            UNION
            SELECT id FROM nfl_markets WHERE id = ANY(p_market_ids)
        )
    ) INTO v_missing;

    IF array_length(v_missing, 1) IS NOT NULL THEN
        RAISE EXCEPTION 'Market IDs not found in any market table: %', v_missing;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- =============================================================================
-- Replace ensure_exchange_slate_and_lineups to no longer require market_type.
-- =============================================================================
DROP FUNCTION ensure_exchange_slate_and_lineups(market_entity_type, UUID[], BIGINT);

CREATE FUNCTION ensure_exchange_slate_and_lineups(
    p_market_ids UUID[],
    p_total_units BIGINT
) RETURNS JSONB AS $$
DECLARE
    v_sorted_ids UUID[];
    v_slate exchange_slates;
    v_num_markets INT;
    v_num_lineups INT;
    v_lineup_index INT;
    v_legs JSONB;
    v_result JSONB;
BEGIN
    IF array_length(p_market_ids, 1) IS NULL OR array_length(p_market_ids, 1) = 0 THEN
        RAISE EXCEPTION 'p_market_ids must not be empty';
    END IF;

    -- Validate that all market IDs exist in at least one market table
    PERFORM validate_market_ids(p_market_ids);

    -- Sort market_ids for consistent storage and lookup
    SELECT ARRAY(SELECT unnest(p_market_ids) ORDER BY 1) INTO v_sorted_ids;

    -- Attempt insert; do nothing on conflict
    INSERT INTO exchange_slates (market_ids, total_units)
    VALUES (v_sorted_ids, p_total_units)
    ON CONFLICT (market_ids) DO NOTHING
    RETURNING * INTO v_slate;

    IF v_slate.id IS NOT NULL THEN
        -- New slate created; generate lineups (2^N combinations of over/under)
        v_num_markets := array_length(v_sorted_ids, 1);
        v_num_lineups := (1 << v_num_markets);

        FOR v_lineup_index IN 0..(v_num_lineups - 1) LOOP
            SELECT jsonb_agg(
                jsonb_build_object(
                    'market_id', v_sorted_ids[idx],
                    'side', CASE
                        WHEN (v_lineup_index >> (v_num_markets - idx)) & 1 = 0
                        THEN 'under' ELSE 'over'
                    END
                ) ORDER BY idx
            ) INTO v_legs
            FROM generate_series(1, v_num_markets) AS idx;

            INSERT INTO exchange_lineups (slate_id, lineup_index, legs)
            VALUES (v_slate.id, v_lineup_index, v_legs);
        END LOOP;
    ELSE
        -- Slate already exists; fetch and validate total_units
        SELECT * INTO v_slate
        FROM exchange_slates
        WHERE market_ids = v_sorted_ids;

        IF v_slate.total_units != p_total_units THEN
            RAISE EXCEPTION 'Slate exists with total_units=%, expected %',
                v_slate.total_units, p_total_units;
        END IF;
    END IF;

    -- Return slate + lineups as JSONB
    SELECT jsonb_build_object(
        'slate', row_to_json(v_slate)::jsonb,
        'lineups', COALESCE((
            SELECT jsonb_agg(row_to_json(l)::jsonb ORDER BY l.lineup_index)
            FROM exchange_lineups l
            WHERE l.slate_id = v_slate.id
        ), '[]'::jsonb)
    ) INTO v_result;

    RETURN v_result;
END;
$$ LANGUAGE plpgsql;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

-- Drop new functions
DROP FUNCTION ensure_exchange_slate_and_lineups(UUID[], BIGINT);
DROP FUNCTION validate_market_ids(UUID[]);

-- Drop new unique constraint
ALTER TABLE exchange_slates
    DROP CONSTRAINT exchange_slates_market_ids_unique;

-- Re-add market_type column, populated from the first market ID in each slate
ALTER TABLE exchange_slates
    ADD COLUMN market_type market_entity_type;

UPDATE exchange_slates
    SET market_type = resolve_market_entity_type(market_ids[1]);

ALTER TABLE exchange_slates
    ALTER COLUMN market_type SET NOT NULL;

-- Re-add old unique constraint
ALTER TABLE exchange_slates
    ADD CONSTRAINT exchange_slates_market_type_market_ids_unique
    UNIQUE (market_type, market_ids);

-- Restore old validate_market_ids with market_type parameter
CREATE FUNCTION validate_market_ids(
    p_market_type market_entity_type,
    p_market_ids UUID[]
) RETURNS VOID AS $$
DECLARE
    v_missing UUID[];
BEGIN
    IF p_market_type = 'nba_market' THEN
        SELECT ARRAY(
            SELECT unnest(p_market_ids)
            EXCEPT
            SELECT id FROM nba_markets WHERE id = ANY(p_market_ids)
        ) INTO v_missing;
    ELSIF p_market_type = 'nfl_market' THEN
        SELECT ARRAY(
            SELECT unnest(p_market_ids)
            EXCEPT
            SELECT id FROM nfl_markets WHERE id = ANY(p_market_ids)
        ) INTO v_missing;
    ELSE
        RAISE EXCEPTION 'Unknown market type: %', p_market_type;
    END IF;

    IF array_length(v_missing, 1) IS NOT NULL THEN
        RAISE EXCEPTION 'Market IDs not found for type %: %', p_market_type, v_missing;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- Restore old ensure_exchange_slate_and_lineups with market_type parameter
CREATE FUNCTION ensure_exchange_slate_and_lineups(
    p_market_type market_entity_type,
    p_market_ids UUID[],
    p_total_units BIGINT
) RETURNS JSONB AS $$
DECLARE
    v_sorted_ids UUID[];
    v_slate exchange_slates;
    v_num_markets INT;
    v_num_lineups INT;
    v_lineup_index INT;
    v_legs JSONB;
    v_result JSONB;
BEGIN
    IF array_length(p_market_ids, 1) IS NULL OR array_length(p_market_ids, 1) = 0 THEN
        RAISE EXCEPTION 'p_market_ids must not be empty';
    END IF;

    -- Validate that all market IDs exist in the corresponding table
    PERFORM validate_market_ids(p_market_type, p_market_ids);

    -- Sort market_ids for consistent storage and lookup
    SELECT ARRAY(SELECT unnest(p_market_ids) ORDER BY 1) INTO v_sorted_ids;

    -- Attempt insert; do nothing on conflict
    INSERT INTO exchange_slates (market_type, market_ids, total_units)
    VALUES (p_market_type, v_sorted_ids, p_total_units)
    ON CONFLICT (market_type, market_ids) DO NOTHING
    RETURNING * INTO v_slate;

    IF v_slate.id IS NOT NULL THEN
        -- New slate created; generate lineups (2^N combinations of over/under)
        v_num_markets := array_length(v_sorted_ids, 1);
        v_num_lineups := (1 << v_num_markets);

        FOR v_lineup_index IN 0..(v_num_lineups - 1) LOOP
            SELECT jsonb_agg(
                jsonb_build_object(
                    'market_id', v_sorted_ids[idx],
                    'side', CASE
                        WHEN (v_lineup_index >> (v_num_markets - idx)) & 1 = 0
                        THEN 'under' ELSE 'over'
                    END
                ) ORDER BY idx
            ) INTO v_legs
            FROM generate_series(1, v_num_markets) AS idx;

            INSERT INTO exchange_lineups (slate_id, lineup_index, legs)
            VALUES (v_slate.id, v_lineup_index, v_legs);
        END LOOP;
    ELSE
        -- Slate already exists; fetch and validate total_units
        SELECT * INTO v_slate
        FROM exchange_slates
        WHERE market_type = p_market_type AND market_ids = v_sorted_ids;

        IF v_slate.total_units != p_total_units THEN
            RAISE EXCEPTION 'Slate exists with total_units=%, expected %',
                v_slate.total_units, p_total_units;
        END IF;
    END IF;

    -- Return slate + lineups as JSONB
    SELECT jsonb_build_object(
        'slate', row_to_json(v_slate)::jsonb,
        'lineups', COALESCE((
            SELECT jsonb_agg(row_to_json(l)::jsonb ORDER BY l.lineup_index)
            FROM exchange_lineups l
            WHERE l.slate_id = v_slate.id
        ), '[]'::jsonb)
    ) INTO v_result;

    RETURN v_result;
END;
$$ LANGUAGE plpgsql;

-- +goose StatementEnd
