#!/bin/bash

# =============================================================================
# Update Go Enums from Database
# =============================================================================
# This script queries PostgreSQL enum types and generates corresponding Go
# type definitions and constants in shared/models/gen/*.
#
# The generated files should NOT be manually edited - they are auto-generated.
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Change to the Database directory (parent of migrations)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DATABASE_DIR="$(dirname "$SCRIPT_DIR")"
cd "$DATABASE_DIR"

# Load environment variables from Database/.env
if [ -f ".env" ]; then
    set -a
    source .env
    set +a
else
    echo -e "${RED}Error: .env file not found in $DATABASE_DIR${NC}"
    echo "Please create a .env file based on .env.example"
    exit 1
fi

# Check if psql is installed
if ! command -v psql &> /dev/null; then
    echo -e "${RED}Error: psql is not installed${NC}"
    echo "Install PostgreSQL client tools"
    exit 1
fi

# Construct SSL mode parameter
PGSSLMODE="require"
if [ -n "$PG_KEY_PATH" ]; then
    PGSSLROOTCERT="sslrootcert=$PG_KEY_PATH"
else
    PGSSLROOTCERT=""
fi

echo -e "${BLUE}Querying database for enum types...${NC}"

# Function to convert snake_case or "space case" to PascalCase
# Example: "in_progress" -> "InProgress"
# Example: "Day To Day" -> "DayToDay"
to_pascal_case() {
    local input="$1"

    # Replace spaces with underscores, then handle underscores
    input=$(echo "$input" | tr ' ' '_')

    # Convert to PascalCase
    echo "$input" | awk -F_ '{for(i=1;i<=NF;i++){$i=toupper(substr($i,1,1)) tolower(substr($i,2))}}1' OFS=""
}

# Function to convert enum type name to Go type name
# Example: "game_status_type" -> "GameStatusType"
# Example: "nfl_play_type" -> "PlayType" (strips nfl_ prefix)
enum_type_to_go_type() {
    local enum_name="$1"

    # Strip _type suffix if present
    enum_name="${enum_name%_type}"

    # Strip nfl_ prefix if present (for NFL-specific enums)
    enum_name="${enum_name#nfl_}"

    # Strip nba_ prefix if present (for NBA-specific enums)
    enum_name="${enum_name#nba_}"

    # Convert to PascalCase
    to_pascal_case "$enum_name"
}

# Function to generate constant name from enum value
# Example: enum_type="game_status_type", value="in_progress" -> "GameStatusInProgress"
value_to_const_name() {
    local enum_type="$1"
    local value="$2"

    # Get the base type name (e.g., "GameStatus" from "game_status_type")
    local base_type=$(enum_type_to_go_type "$enum_type")

    # Convert value to PascalCase (e.g., "in_progress" -> "InProgress")
    local value_pascal=$(to_pascal_case "$value")

    # Combine: GameStatus + InProgress = GameStatusInProgress
    echo "${base_type}${value_pascal}"
}

# Query all enum types and their values from the public schema only.
# Supabase creates internal enums in other schemas (auth, storage, etc.) that
# our Go code never uses directly, so we exclude them.
ENUM_QUERY="
SELECT
    t.typname as enum_name,
    array_agg(e.enumlabel ORDER BY e.enumsortorder) as enum_values
FROM pg_type t
JOIN pg_enum e ON t.oid = e.enumtypid
JOIN pg_namespace n ON t.typnamespace = n.oid
WHERE n.nspname = 'public'
GROUP BY t.typname
ORDER BY t.typname;
"

# Execute query and store results
ENUM_DATA=$(PGPASSWORD="$PG_PASSWORD" psql -h "$PG_HOST" -p "$PG_PORT" -U "$PG_USER" -d "$PG_DATABASE" -t -A -F'|' -c "$ENUM_QUERY" 2>&1)

if [ $? -ne 0 ]; then
    echo -e "${RED}Error querying database:${NC}"
    echo "$ENUM_DATA"
    exit 1
fi

# Create output directories
SHARED_MODELS_DIR="../shared/models"
GEN_DIR="$SHARED_MODELS_DIR/gen"
NFL_GEN_DIR="$GEN_DIR/nfl"
NBA_GEN_DIR="$GEN_DIR/nba"

mkdir -p "$GEN_DIR"
mkdir -p "$NFL_GEN_DIR"
mkdir -p "$NBA_GEN_DIR"

# Initialize output files
GENERAL_ENUMS_FILE="$GEN_DIR/enums.go"
NFL_ENUMS_FILE="$NFL_GEN_DIR/enums.go"
NBA_ENUMS_FILE="$NBA_GEN_DIR/enums.go"

# Write headers
cat > "$GENERAL_ENUMS_FILE" << 'EOF'
// Code generated by update_go_enums.sh. DO NOT EDIT.
// This file is auto-generated from database enum types.

package gen

EOF

cat > "$NFL_ENUMS_FILE" << 'EOF'
// Code generated by update_go_enums.sh. DO NOT EDIT.
// This file is auto-generated from database enum types.

package nfl

EOF

cat > "$NBA_ENUMS_FILE" << 'EOF'
// Code generated by update_go_enums.sh. DO NOT EDIT.
// This file is auto-generated from database enum types.

package nba

EOF

# Process each enum type
echo -e "${BLUE}Generating Go enum types...${NC}"

while IFS='|' read -r enum_name enum_values_str; do
    # Skip empty lines
    [ -z "$enum_name" ] && continue

    # Convert PostgreSQL array format {val1,val2} to space-separated values
    enum_values=$(echo "$enum_values_str" | tr -d '{}' | tr ',' '\n')

    # Determine output file based on enum name
    if [[ "$enum_name" == nfl_* ]]; then
        OUTPUT_FILE="$NFL_ENUMS_FILE"
        echo -e "${YELLOW}  - $enum_name (NFL-specific)${NC}"
    elif [[ "$enum_name" == nba_* ]]; then
        OUTPUT_FILE="$NBA_ENUMS_FILE"
        echo -e "${YELLOW}  - $enum_name (NBA-specific)${NC}"
    else
        OUTPUT_FILE="$GENERAL_ENUMS_FILE"
        echo -e "${YELLOW}  - $enum_name (general)${NC}"
    fi

    # Get Go type name
    GO_TYPE=$(enum_type_to_go_type "$enum_name")

    # Write type definition
    echo "// ${GO_TYPE} represents the ${enum_name} database enum" >> "$OUTPUT_FILE"
    echo "type ${GO_TYPE} string" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"

    # Write constants
    echo "const (" >> "$OUTPUT_FILE"

    while IFS= read -r value; do
        [ -z "$value" ] && continue
        CONST_NAME=$(value_to_const_name "$enum_name" "$value")
        echo "	${CONST_NAME} ${GO_TYPE} = \"${value}\"" >> "$OUTPUT_FILE"
    done <<< "$enum_values"

    echo ")" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"

done <<< "$ENUM_DATA"

echo -e "${GREEN}✅ Generated enum files:${NC}"
echo -e "${GREEN}   - $GENERAL_ENUMS_FILE${NC}"
echo -e "${GREEN}   - $NFL_ENUMS_FILE${NC}"
echo -e "${GREEN}   - $NBA_ENUMS_FILE${NC}"
