pub mod entry_pool;
pub mod math_utils;
pub mod pool_utils;

pub mod matching_service_package {
    tonic::include_proto!("matching_service_package"); // this is generated by tonic based on the "MatchingServicePackage" in the proto file
}
