use tonic::{transport::Server, Request, Response, Status};
use std::sync::{Arc, Mutex};
use std::collections::BTreeMap;
use tokio_stream::StreamExt;
use tokio_stream::wrappers::ReceiverStream;
use std::pin::Pin;
use futures::Stream;

// The Rust module name "matching_server_service_server" is generated by tonic based on the service name
// defined in the .proto file. In your proto, the service is named "MatchingServerService":
//
//   service MatchingServerService { ... }
//
// tonic converts the service name to snake_case and appends "_server" to form the module name.
// That's why the generated module is "matching_server_service_server". Same goes with the generated
// "MatchingServerServiceServer".
use matching_server::matching_service_package::matching_server_service_server::{MatchingServerService, MatchingServerServiceServer};
// these "use" lines import the corresponding Rust structs from the generated module "service".
use matching_server::matching_service_package::{
    Heartbeat, OrderNew, OrderCancel,
    HeartbeatResponseEnvelope, OrderNewResponseEnvelope, OrderCancelResponseEnvelope,
    MessageBase, SequencedMessageBase, ResponseBase, FallibleBase,
    MessageType, VersionMajor, VersionMinor,
    OrderNewAcknowledgement, OrderCancelAcknowledgement, OrderElimination, FillEvent,
};

use matching_server::pool_manager::PoolManager;

/// Trait for messages that have sequence numbers and can be queued.
trait SequencedMessage: Sized {
    /// Extracts the sequence number from the message.
    fn sequence_number(&self) -> Result<u64, Status>;

    /// Converts this message into a PendingMessage variant.
    fn into_pending(self) -> PendingMessage;
}

impl SequencedMessage for OrderNew {
    fn sequence_number(&self) -> Result<u64, Status> {
        self.sequenced_message_base
            .as_ref()
            .ok_or_else(|| Status::invalid_argument("Missing sequenced_message_base"))
            .map(|base| base.sequence_number)
    }

    fn into_pending(self) -> PendingMessage {
        PendingMessage::OrderNew(self)
    }
}

impl SequencedMessage for OrderCancel {
    fn sequence_number(&self) -> Result<u64, Status> {
        self.sequenced_message_base
            .as_ref()
            .ok_or_else(|| Status::invalid_argument("Missing sequenced_message_base"))
            .map(|base| base.sequence_number)
    }

    fn into_pending(self) -> PendingMessage {
        PendingMessage::OrderCancel(self)
    }
}

/// Represents a pending message waiting to be processed when its sequence number becomes current.
#[derive(Debug)]
enum PendingMessage {
    OrderNew(OrderNew),
    OrderCancel(OrderCancel),
}

/// Inner state of the MatcherService, wrapped in Arc to allow cloning into spawned tasks.
/// This enables the service to share state across multiple async tasks while maintaining
/// thread-safe access through Mutex.
#[derive(Clone)]
struct ServiceState {
    /// Tracks the next expected sequence number from sequenced messages.
    expected_next_sequence_number: Arc<Mutex<u64>>,

    /// Queue of out-of-order messages waiting to be processed.
    pending_messages: Arc<Mutex<BTreeMap<u64, PendingMessage>>>,

    /// The pool manager that handles order matching logic.
    pool_manager: Arc<Mutex<PoolManager>>,

    /// Tracks the next response sequence number (shared across OrderNew and OrderCancel streams).
    next_response_sequence_number: Arc<Mutex<u64>>,

    /// Response channels - set when clients connect to each stream type.
    heartbeat_tx: Arc<Mutex<Option<tokio::sync::mpsc::Sender<Result<HeartbeatResponseEnvelope, Status>>>>>,
    order_new_tx: Arc<Mutex<Option<tokio::sync::mpsc::Sender<Result<OrderNewResponseEnvelope, Status>>>>>,
    order_cancel_tx: Arc<Mutex<Option<tokio::sync::mpsc::Sender<Result<OrderCancelResponseEnvelope, Status>>>>>,
}

// #[derive(Debug)] is a Rust attribute that automatically implements the Debug trait for the struct that follows.
// - Debug allows the struct to be formatted using {:?}, which is useful for printing and debugging.
pub struct MatcherService {
    state: ServiceState,
}

impl MatcherService {
    pub fn new() -> Self {
        Self {
            state: ServiceState {
                expected_next_sequence_number: Arc::new(Mutex::new(0)),
                pending_messages: Arc::new(Mutex::new(BTreeMap::new())),
                pool_manager: Arc::new(Mutex::new(PoolManager::new())),
                next_response_sequence_number: Arc::new(Mutex::new(0)),
                heartbeat_tx: Arc::new(Mutex::new(None)),
                order_new_tx: Arc::new(Mutex::new(None)),
                order_cancel_tx: Arc::new(Mutex::new(None)),
            },
        }
    }

    /// Generic helper to process a single sequenced message.
    async fn handle_single_message<T: SequencedMessage>(&self, message: T) -> Result<(), Status> {
        let sequence_number = message.sequence_number()?;
        self.handle_sequenced_message(sequence_number, message.into_pending())
            .await?;
        Ok(())
    }

    /// Generic helper to process a stream of sequenced messages.
    async fn handle_message_stream<T: SequencedMessage>(
        &self,
        mut stream: tonic::Streaming<T>,
    ) -> Result<(), Status> {
        while let Some(message) = stream.next().await {
            let message = message?;
            self.handle_single_message(message).await?;
        }
        Ok(())
    }

    /// Processes a sequenced message, either immediately if it's the next expected sequence,
    /// or queues it if it arrives out of order.
    /// Returns Ok(true) if the message was processed, Ok(false) if it was queued.
    /// Panics if the sequence number is invalid (e.g., duplicate or too old).
    async fn handle_sequenced_message(
        &self,
        sequence_number: u64,
        message: PendingMessage,
    ) -> Result<bool, Status> {
        // Check sequence number and update state in a scope to ensure locks are dropped
        let should_process = {
            let mut expected = self.state.expected_next_sequence_number.lock().unwrap();

            if sequence_number < *expected {
                // Message is too old or duplicate - this should never happen, terminate process
                eprintln!(
                    "FATAL: Received message with sequence {} but expected {}. Duplicate or out-of-order message.",
                    sequence_number, *expected
                );
                std::process::exit(1);
            } else if sequence_number == *expected {
                // This is the expected message, increment counter
                *expected += 1;
                true
            } else {
                // Message arrived early, queue it for later
                let mut queue = self.state.pending_messages.lock().unwrap();
                if queue.contains_key(&sequence_number) {
                    eprintln!(
                        "FATAL: Received duplicate message with sequence {}. Message already in queue.",
                        sequence_number
                    );
                    std::process::exit(1);
                }
                queue.insert(sequence_number, message);
                return Ok(false);
            }
        }; // Locks are dropped here

        if should_process {
            // Process the message
            self.process_message(message).await?;

            // Process any queued messages that are now ready
            self.process_queued_messages().await?;
            Ok(true)
        } else {
            Ok(false)
        }
    }

    /// Processes queued messages that are now ready (their sequence number matches expected).
    async fn process_queued_messages(&self) -> Result<(), Status> {
        loop {
            // Extract next message from queue in a scope to ensure locks are dropped
            let next_message = {
                let mut expected = self.state.expected_next_sequence_number.lock().unwrap();
                let mut queue = self.state.pending_messages.lock().unwrap();

                if let Some(message) = queue.remove(&*expected) {
                    *expected += 1;
                    Some(message)
                } else {
                    None
                }
            }; // Locks are dropped here

            if let Some(message) = next_message {
                self.process_message(message).await?;
            } else {
                // No message with the expected sequence number in queue
                break;
            }
        }
        Ok(())
    }

    /// Helper to get the next response sequence number
    fn get_next_response_sequence(&self) -> u64 {
        let mut seq = self.state.next_response_sequence_number.lock().unwrap();
        let current = *seq;
        *seq += 1;
        current
    }

    /// Helper to create MessageBase with version and message type
    fn create_message_base(message_type: MessageType) -> MessageBase {
        MessageBase {
            version_major: VersionMajor::Value as u32,
            version_minor: VersionMinor::Value as u32,
            message_type: message_type as i32,
        }
    }

    /// Actually processes a message and sends the response to the appropriate channel.
    /// This is where cross-message-type interactions work correctly: when processing
    /// an OrderNew triggers a queued OrderCancel, each response goes to its own channel.
    async fn process_message(&self, message: PendingMessage) -> Result<(), Status> {
        match message {
            PendingMessage::OrderNew(order) => {
                println!("Processing OrderNew: {:?}", order);

                // Extract request sequence number
                let request_sequence_number = order
                    .sequenced_message_base
                    .as_ref()
                    .ok_or_else(|| Status::internal("Missing sequenced_message_base"))?
                    .sequence_number;

                // Extract body
                let body = order
                    .body
                    .ok_or_else(|| Status::invalid_argument("Missing order body"))?;

                // Process the order through the pool manager
                let result = {
                    let mut pool_manager = self.state.pool_manager.lock().unwrap();
                    pool_manager.create_entry(body)
                };

                // Get the tx channel and clone it to avoid holding the lock across await
                let tx = {
                    let tx_guard = self.state.order_new_tx.lock().unwrap();
                    tx_guard.as_ref().unwrap_or_else(|| {
                        eprintln!("FATAL: OrderNew tx channel is None");
                        std::process::exit(1);
                    }).clone()
                };

                match result {
                    Ok((elimination_bodies, ack_body, fill_event_bodies, market_entry_elimination_bodies)) => {
                        // Send OrderElimination messages first (prior to acknowledgement)
                        for elimination_body in elimination_bodies {
                            let elimination_response = OrderNewResponseEnvelope {
                                contents: Some(
                                    matching_server::matching_service_package::order_new_response_envelope::Contents::Elimination(
                                        OrderElimination {
                                            message_base: Some(Self::create_message_base(MessageType::OrderElimination)),
                                            sequenced_message_base: Some(SequencedMessageBase {
                                                sequence_number: self.get_next_response_sequence(),
                                            }),
                                            body: Some(elimination_body),
                                        }
                                    )
                                ),
                            };

                            tx.send(Ok(elimination_response)).await.map_err(|_| {
                                Status::internal("Failed to send OrderElimination")
                            })?;
                        }

                        // Send OrderNewAcknowledgement (success)
                        let ack_response = OrderNewResponseEnvelope {
                            contents: Some(
                                matching_server::matching_service_package::order_new_response_envelope::Contents::Acknowledgement(
                                    OrderNewAcknowledgement {
                                        message_base: Some(Self::create_message_base(MessageType::OrderNewAcknowledgement)),
                                        sequenced_message_base: Some(SequencedMessageBase {
                                            sequence_number: self.get_next_response_sequence(),
                                        }),
                                        response_base: Some(ResponseBase {
                                            request_sequence_number,
                                        }),
                                        fallible_base: Some(FallibleBase {
                                            success: true,
                                            error_description: String::new(),
                                        }),
                                        body: Some(ack_body),
                                    }
                                )
                            ),
                        };

                        tx.send(Ok(ack_response)).await.map_err(|_| {
                            Status::internal("Failed to send OrderNewAcknowledgement")
                        })?;

                        // Send FillEvents
                        for fill_body in fill_event_bodies {
                            let fill_response = OrderNewResponseEnvelope {
                                contents: Some(
                                    matching_server::matching_service_package::order_new_response_envelope::Contents::Fill(
                                        FillEvent {
                                            message_base: Some(Self::create_message_base(MessageType::OrderFill)),
                                            sequenced_message_base: Some(SequencedMessageBase {
                                                sequence_number: self.get_next_response_sequence(),
                                            }),
                                            body: Some(fill_body),
                                        }
                                    )
                                ),
                            };

                            tx.send(Ok(fill_response)).await.map_err(|_| {
                                Status::internal("Failed to send FillEvent")
                            })?;
                        }

                        // Send market entry OrderElimination messages (after fill events)
                        for elimination_body in market_entry_elimination_bodies {
                            let elimination_response = OrderNewResponseEnvelope {
                                contents: Some(
                                    matching_server::matching_service_package::order_new_response_envelope::Contents::Elimination(
                                        OrderElimination {
                                            message_base: Some(Self::create_message_base(MessageType::OrderElimination)),
                                            sequenced_message_base: Some(SequencedMessageBase {
                                                sequence_number: self.get_next_response_sequence(),
                                            }),
                                            body: Some(elimination_body),
                                        }
                                    )
                                ),
                            };

                            tx.send(Ok(elimination_response)).await.map_err(|_| {
                                Status::internal("Failed to send market entry OrderElimination")
                            })?;
                        }
                    }
                    Err(error_msg) => {
                        // Send OrderNewAcknowledgement (failure)
                        let ack_response = OrderNewResponseEnvelope {
                            contents: Some(
                                matching_server::matching_service_package::order_new_response_envelope::Contents::Acknowledgement(
                                    OrderNewAcknowledgement {
                                        message_base: Some(Self::create_message_base(MessageType::OrderNewAcknowledgement)),
                                        sequenced_message_base: Some(SequencedMessageBase {
                                            sequence_number: self.get_next_response_sequence(),
                                        }),
                                        response_base: Some(ResponseBase {
                                            request_sequence_number,
                                        }),
                                        fallible_base: Some(FallibleBase {
                                            success: false,
                                            error_description: error_msg,
                                        }),
                                        body: None,
                                    }
                                )
                            ),
                        };

                        tx.send(Ok(ack_response)).await.map_err(|_| {
                            Status::internal("Failed to send OrderNewAcknowledgement")
                        })?;
                    }
                }

                Ok(())
            }
            PendingMessage::OrderCancel(cancel) => {
                println!("Processing OrderCancel: {:?}", cancel);

                // Extract request sequence number
                let request_sequence_number = cancel
                    .sequenced_message_base
                    .as_ref()
                    .ok_or_else(|| Status::internal("Missing sequenced_message_base"))?
                    .sequence_number;

                // Extract body
                let body = cancel
                    .body
                    .ok_or_else(|| Status::invalid_argument("Missing cancel body"))?;

                // Process the cancel through the pool manager
                let result = {
                    let mut pool_manager = self.state.pool_manager.lock().unwrap();
                    pool_manager.cancel_entry(body)
                };

                // Get the tx channel and clone it to avoid holding the lock across await
                let tx = {
                    let tx_guard = self.state.order_cancel_tx.lock().unwrap();
                    tx_guard.as_ref().unwrap_or_else(|| {
                        eprintln!("FATAL: OrderCancel tx channel is None");
                        std::process::exit(1);
                    }).clone()
                };

                match result {
                    Ok(ack_body) => {
                        // Send OrderCancelAcknowledgement (success)
                        let ack_response = OrderCancelResponseEnvelope {
                            contents: Some(
                                matching_server::matching_service_package::order_cancel_response_envelope::Contents::Acknowledgement(
                                    OrderCancelAcknowledgement {
                                        message_base: Some(Self::create_message_base(MessageType::OrderCancelAcknowledgement)),
                                        sequenced_message_base: Some(SequencedMessageBase {
                                            sequence_number: self.get_next_response_sequence(),
                                        }),
                                        response_base: Some(ResponseBase {
                                            request_sequence_number,
                                        }),
                                        fallible_base: Some(FallibleBase {
                                            success: true,
                                            error_description: String::new(),
                                        }),
                                        body: Some(ack_body),
                                    }
                                )
                            ),
                        };

                        tx.send(Ok(ack_response)).await.map_err(|_| {
                            Status::internal("Failed to send OrderCancelAcknowledgement")
                        })?;
                    }
                    Err(error_msg) => {
                        // Send OrderCancelAcknowledgement (failure)
                        let ack_response = OrderCancelResponseEnvelope {
                            contents: Some(
                                matching_server::matching_service_package::order_cancel_response_envelope::Contents::Acknowledgement(
                                    OrderCancelAcknowledgement {
                                        message_base: Some(Self::create_message_base(MessageType::OrderCancelAcknowledgement)),
                                        sequenced_message_base: Some(SequencedMessageBase {
                                            sequence_number: self.get_next_response_sequence(),
                                        }),
                                        response_base: Some(ResponseBase {
                                            request_sequence_number,
                                        }),
                                        fallible_base: Some(FallibleBase {
                                            success: false,
                                            error_description: error_msg,
                                        }),
                                        body: None,
                                    }
                                )
                            ),
                        };

                        tx.send(Ok(ack_response)).await.map_err(|_| {
                            Status::internal("Failed to send OrderCancelAcknowledgement")
                        })?;
                    }
                }

                Ok(())
            }
        }
    }

    /// Generic helper to set up a bidirectional stream for sequenced messages.
    /// This reduces code duplication between on_order_new and on_order_cancel handlers.
    ///
    /// Type parameters:
    /// - T: The incoming message type (OrderNew or OrderCancel)
    /// - R: The response envelope type (OrderNewResponseEnvelope or OrderCancelResponseEnvelope)
    ///
    /// Returns a stream that persists for the client session.
    fn setup_sequenced_stream<T, R>(
        &self,
        in_stream: tonic::Streaming<T>,
        tx_storage: &Arc<Mutex<Option<tokio::sync::mpsc::Sender<Result<R, Status>>>>>,
        stream_name: &'static str,
    ) -> Pin<Box<dyn Stream<Item = Result<R, Status>> + Send>>
    where
        T: SequencedMessage + Send + 'static,
        R: Send + 'static,
    {
        // Create a channel for sending responses back to the client
        let (tx, rx) = tokio::sync::mpsc::channel(100);

        // Store the sender so process_message can send responses
        *tx_storage.lock().unwrap() = Some(tx);

        // Clone the state for the spawned task (cloning Arc pointers, not the actual data)
        let state = self.state.clone();

        // Spawn a task to process incoming messages
        tokio::spawn(async move {
            // Create a temporary MatcherService with the cloned state
            let service = MatcherService { state };

            if let Err(e) = service.handle_message_stream(in_stream).await {
                eprintln!("{} stream error: {:?}", stream_name, e);
            }
            println!("{} stream closed", stream_name);
        });

        println!("{} stream created", stream_name);

        // Return the output stream
        Box::pin(ReceiverStream::new(rx))
    }
}

#[tonic::async_trait]
// This line starts an implementation block in Rust.
// "impl Trait for Type" means we are providing the required method implementations for the trait "Trait" for the type "Type".
// Here, "impl MatchingServerService for MatcherService" means we are implementing the gRPC service trait "MatchingServerService" (generated from the proto file) for our struct "MatcherService".
// This allows "MatcherService" to act as a gRPC server for the defined service.
impl MatchingServerService for MatcherService {
    // Define stream types as Pin<Box<dyn Stream<...>>> to allow flexible implementations
    // These streams represent the stable connection that persists for the client session
    type CreateHeartbeatResponseStreamStream = Pin<Box<dyn Stream<Item = Result<HeartbeatResponseEnvelope, Status>> + Send>>;
    type CreateOrderNewResponseStreamStream = Pin<Box<dyn Stream<Item = Result<OrderNewResponseEnvelope, Status>> + Send>>;
    type CreateOrderCancelResponseStreamStream = Pin<Box<dyn Stream<Item = Result<OrderCancelResponseEnvelope, Status>> + Send>>;

    /// Handles heartbeat bidirectional stream.
    /// This handler is called ONCE when the client establishes the connection.
    /// The returned stream is the stable connection used throughout the session.
    async fn create_heartbeat_response_stream(
        &self,
        request: Request<tonic::Streaming<Heartbeat>>,
    ) -> Result<Response<Self::CreateHeartbeatResponseStreamStream>, Status> {
        let mut in_stream = request.into_inner();

        // Create a channel for sending responses back to the client
        // Buffer size of 100 allows for some backpressure handling
        let (tx, rx) = tokio::sync::mpsc::channel(100);

        // Store the sender for potential use by other parts of the system
        *self.state.heartbeat_tx.lock().unwrap() = Some(tx.clone());

        // Spawn a task to handle incoming heartbeats
        // This task runs for the lifetime of the client connection
        tokio::spawn(async move {
            let mut heartbeat_count = 0u64;
            while let Some(result) = in_stream.next().await {
                match result {
                    Ok(heartbeat) => {
                        heartbeat_count += 1;
                        println!("Received heartbeat #{}", heartbeat_count);

                        // Echo the heartbeat back to the client
                        let response = HeartbeatResponseEnvelope {
                            contents: Some(
                                matching_server::matching_service_package::heartbeat_response_envelope::Contents::Heartbeat(heartbeat)
                            ),
                        };

                        // Send the response through the channel
                        // If send fails, the client has disconnected, so break
                        if tx.send(Ok(response)).await.is_err() {
                            println!("Failed to send heartbeat response - client disconnected");
                            break;
                        }
                        println!("Sent heartbeat response #{}", heartbeat_count);
                    }
                    Err(status) => {
                        // Stream error occurred, log it and break
                        eprintln!("Heartbeat stream error: {:?}", status);
                        break;
                    }
                }
            }
            println!("Heartbeat stream closed (received {} heartbeats total)", heartbeat_count);
        });
        println!("Heartbeat stream created");

        // Create the output stream from the receiver
        // This stream is returned to the client and persists for the session
        let out_stream = ReceiverStream::new(rx);
        Ok(Response::new(Box::pin(out_stream) as Self::CreateHeartbeatResponseStreamStream))
    }

    /// Handles OrderNew bidirectional stream.
    /// This handler is called ONCE when the client establishes the connection.
    /// The returned stream persists for the lifetime of the client session.
    async fn create_order_new_response_stream(
        &self,
        request: Request<tonic::Streaming<OrderNew>>,
    ) -> Result<Response<Self::CreateOrderNewResponseStreamStream>, Status> {
        let in_stream = request.into_inner();
        let out_stream = self.setup_sequenced_stream(in_stream, &self.state.order_new_tx, "OrderNew");
        Ok(Response::new(out_stream))
    }

    /// Handles OrderCancel bidirectional stream.
    /// This handler is called ONCE when the client establishes the connection.
    /// The returned stream persists for the lifetime of the client session.
    async fn create_order_cancel_response_stream(
        &self,
        request: Request<tonic::Streaming<OrderCancel>>,
    ) -> Result<Response<Self::CreateOrderCancelResponseStreamStream>, Status> {
        let in_stream = request.into_inner();
        let out_stream = self.setup_sequenced_stream(in_stream, &self.state.order_cancel_tx, "OrderCancel");
        Ok(Response::new(out_stream))
    }
}

/// Configuration loaded from .env file
struct Config {
    engine_port: u16,
    #[allow(dead_code)] // Will be used in the future
    heartbeat_interval_ms: u64,
}

impl Config {
    fn load() -> Result<Self, Box<dyn std::error::Error>> {
        // Load .env file from current directory
        dotenvy::dotenv().map_err(|e| {
            format!("Failed to load .env file: {}. Please ensure .env file exists with required fields (ENGINE_PORT, HEARTBEAT_INTERVAL_MS)", e)
        })?;

        // Read required ENGINE_PORT
        let engine_port = std::env::var("ENGINE_PORT")
            .map_err(|_| "Missing required environment variable: ENGINE_PORT")?
            .parse::<u16>()
            .map_err(|_| "ENGINE_PORT must be a valid port number (0-65535)")?;

        // Read optional HEARTBEAT_INTERVAL_MS with default of 0 (disabled)
        let heartbeat_interval_ms = std::env::var("HEARTBEAT_INTERVAL_MS")
            .unwrap_or_else(|_| "0".to_string())
            .parse::<u64>()
            .map_err(|_| "HEARTBEAT_INTERVAL_MS must be a valid number")?;

        Ok(Config {
            engine_port,
            heartbeat_interval_ms,
        })
    }
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Load configuration from .env file
    let config = Config::load()?;

    // Construct server address using configured port
    let addr = format!("[::1]:{}", config.engine_port).parse()?;
    let matcher = MatcherService::new();

    println!("Matcher gRPC server listening on {}", addr);

    Server::builder()
        .add_service(MatchingServerServiceServer::new(matcher))
        .serve(addr)
        .await?;

    Ok(())
}
