use tonic::{transport::Server, Request, Response, Status};
use std::sync::Mutex;
use std::collections::BTreeMap;
use tokio_stream::StreamExt;

// The Rust module name "matching_server_service_server" is generated by tonic based on the service name
// defined in the .proto file. In your proto, the service is named "MatchingServerService":
//
//   service MatchingServerService { ... }
//
// tonic converts the service name to snake_case and appends "_server" to form the module name.
// That's why the generated module is "matching_server_service_server". Same goes with the generated
// "MatchingServerServiceServer".
use matching_server::matching_service_package::matching_server_service_server::{MatchingServerService, MatchingServerServiceServer};
// these "use" lines import the corresponding Rust structs from the generated module "service".
use matching_server::matching_service_package::{MessageType, OrderType};
use matching_server::matching_service_package::{MessageBase, SequencedMessageBase, ResponseBase, FallibleBase};
use matching_server::matching_service_package::{Heartbeat, GeneralReject, OrderNew, OrderNewAcknowledgement, OrderCancel, OrderCancelAcknowledgement, OrderElimination, FillEvent};
use matching_server::matching_service_package::{HeartbeatResponseEnvelope, OrderNewResponseEnvelope, OrderCancelResponseEnvelope};

/// Trait for messages that have sequence numbers and can be queued.
trait SequencedMessage: Sized {
    /// Extracts the sequence number from the message.
    fn sequence_number(&self) -> Result<u64, Status>;

    /// Converts this message into a PendingMessage variant.
    fn into_pending(self) -> PendingMessage;
}

impl SequencedMessage for OrderNew {
    fn sequence_number(&self) -> Result<u64, Status> {
        self.sequenced_message_base
            .as_ref()
            .ok_or_else(|| Status::invalid_argument("Missing sequenced_message_base"))
            .map(|base| base.sequence_number)
    }

    fn into_pending(self) -> PendingMessage {
        PendingMessage::OrderNew(self)
    }
}

impl SequencedMessage for OrderCancel {
    fn sequence_number(&self) -> Result<u64, Status> {
        self.sequenced_message_base
            .as_ref()
            .ok_or_else(|| Status::invalid_argument("Missing sequenced_message_base"))
            .map(|base| base.sequence_number)
    }

    fn into_pending(self) -> PendingMessage {
        PendingMessage::OrderCancel(self)
    }
}

/// Represents a pending message waiting to be processed when its sequence number becomes current.
#[derive(Debug)]
enum PendingMessage {
    OrderNew(OrderNew),
    OrderCancel(OrderCancel),
}

// #[derive(Debug)] is a Rust attribute that automatically implements the Debug trait for the struct that follows.
// - Debug allows the struct to be formatted using {:?}, which is useful for printing and debugging.
#[derive(Debug)]
pub struct MatcherService {
    /// Tracks the next expected sequence number from sequenced messages.
    /// Wrapped in Mutex to allow mutation through &self references in async handlers.
    expected_next_sequence_number: Mutex<u64>,

    /// Queue of out-of-order messages waiting to be processed.
    /// Key is the sequence number, value is the pending message.
    /// Wrapped in Mutex to allow mutation through &self references in async handlers.
    pending_messages: Mutex<BTreeMap<u64, PendingMessage>>,
}

impl MatcherService {
    pub fn new() -> Self {
        Self {
            expected_next_sequence_number: Mutex::new(0),
            pending_messages: Mutex::new(BTreeMap::new()),
        }
    }

    /// Generic helper to process a single sequenced message.
    async fn handle_single_message<T: SequencedMessage>(&self, message: T) -> Result<(), Status> {
        let sequence_number = message.sequence_number()?;
        self.handle_sequenced_message(sequence_number, message.into_pending())
            .await?;
        Ok(())
    }

    /// Generic helper to process a stream of sequenced messages.
    async fn handle_message_stream<T: SequencedMessage>(
        &self,
        mut stream: tonic::Streaming<T>,
    ) -> Result<(), Status> {
        while let Some(message) = stream.next().await {
            let message = message?;
            self.handle_single_message(message).await?;
        }
        Ok(())
    }

    /// Processes a sequenced message, either immediately if it's the next expected sequence,
    /// or queues it if it arrives out of order.
    /// Returns Ok(true) if the message was processed, Ok(false) if it was queued.
    /// Panics if the sequence number is invalid (e.g., duplicate or too old).
    async fn handle_sequenced_message(
        &self,
        sequence_number: u64,
        message: PendingMessage,
    ) -> Result<bool, Status> {
        // Check sequence number and update state in a scope to ensure locks are dropped
        let should_process = {
            let mut expected = self.expected_next_sequence_number.lock().unwrap();

            if sequence_number < *expected {
                // Message is too old or duplicate - this should never happen, panic
                panic!(
                    "FATAL: Received message with sequence {} but expected {}. Duplicate or out-of-order message!",
                    sequence_number, *expected
                );
            } else if sequence_number == *expected {
                // This is the expected message, increment counter
                *expected += 1;
                true
            } else {
                // Message arrived early, queue it for later
                let mut queue = self.pending_messages.lock().unwrap();
                queue.insert(sequence_number, message);
                return Ok(false);
            }
        }; // Locks are dropped here

        if should_process {
            // Process the message
            self.process_message(message).await?;

            // Process any queued messages that are now ready
            self.process_queued_messages().await?;
            Ok(true)
        } else {
            Ok(false)
        }
    }

    /// Processes queued messages that are now ready (their sequence number matches expected).
    async fn process_queued_messages(&self) -> Result<(), Status> {
        loop {
            // Extract next message from queue in a scope to ensure locks are dropped
            let next_message = {
                let mut expected = self.expected_next_sequence_number.lock().unwrap();
                let mut queue = self.pending_messages.lock().unwrap();

                if let Some(message) = queue.remove(&*expected) {
                    *expected += 1;
                    Some(message)
                } else {
                    None
                }
            }; // Locks are dropped here

            if let Some(message) = next_message {
                self.process_message(message).await?;
            } else {
                // No message with the expected sequence number in queue
                break;
            }
        }
        Ok(())
    }

    /// Actually processes a message (placeholder implementation).
    async fn process_message(&self, message: PendingMessage) -> Result<(), Status> {
        match message {
            PendingMessage::OrderNew(order) => {
                // TODO: Implement actual order processing logic
                println!("Processing OrderNew: {:?}", order);
                Ok(())
            }
            PendingMessage::OrderCancel(cancel) => {
                // TODO: Implement actual cancel processing logic
                println!("Processing OrderCancel: {:?}", cancel);
                Ok(())
            }
        }
    }
}

#[tonic::async_trait]
// This line starts an implementation block in Rust.
// "impl Trait for Type" means we are providing the required method implementations for the trait "Trait" for the type "Type".
// Here, "impl MatchingServerService for MatcherService" means we are implementing the gRPC service trait "MatchingServerService" (generated from the proto file) for our struct "MatcherService".
// This allows "MatcherService" to act as a gRPC server for the defined service.
impl MatchingServerService for MatcherService {
    // Even though the function's return type is defined in the proto file, tonic generates a Rust trait
    // with associated types for each streaming response. This is because, in Rust, the concrete type
    // implementing the stream (i.e., what will actually yield the response messages) must be specified
    // in the trait implementation. The proto file only describes the message types, not the actual
    // stream implementation. By requiring these type definitions, tonic allows you to choose how the
    // stream is produced (e.g., using tonic's Streaming<T>, a custom stream, etc.), providing flexibility
    // and type safety in the Rust service implementation.
    type OnHeartbeatStream = tonic::codec::Streaming<HeartbeatResponseEnvelope>;
    type OnOrderNewStream = tonic::codec::Streaming<OrderNewResponseEnvelope>;
    type OnOrderCancelStream = tonic::codec::Streaming<OrderCancelResponseEnvelope>;

    async fn on_heartbeat(
        &self,
        _request: Request<tonic::Streaming<Heartbeat>>,
    ) -> Result<Response<Self::OnHeartbeatStream>, Status> {
        unimplemented!("on_heartbeat not yet implemented")
    }

    async fn on_order_new(
        &self,
        request: Request<tonic::Streaming<OrderNew>>,
    ) -> Result<Response<Self::OnOrderNewStream>, Status> {
        let stream = request.into_inner();
        self.handle_message_stream(stream).await?;

        // TODO: Return actual response stream
        unimplemented!("Response stream generation not yet implemented")
    }

    async fn on_order_cancel(
        &self,
        request: Request<tonic::Streaming<OrderCancel>>,
    ) -> Result<Response<Self::OnOrderCancelStream>, Status> {
        let stream = request.into_inner();
        self.handle_message_stream(stream).await?;

        // TODO: Return actual response stream
        unimplemented!("Response stream generation not yet implemented")
    }
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let addr = "[::1]:50051".parse()?;
    let matcher = MatcherService::new();

    println!("Matcher gRPC server listening on {}", addr);

    Server::builder()
        .add_service(MatchingServerServiceServer::new(matcher))
        .serve(addr)
        .await?;

    Ok(())
}
