use tonic::{transport::Server, Request, Response, Status};

// The Rust module name "matching_server_service_server" is generated by tonic based on the service name
// defined in the .proto file. In your proto, the service is named "MatchingServerService":
//
//   service MatchingServerService { ... }
//
// tonic converts the service name to snake_case and appends "_server" to form the module name.
// That's why the generated module is "matching_server_service_server". Same goes with the generated
// "MatchingServerServiceServer".
use matching_server::matching_service_package::matching_server_service_server::{MatchingServerService, MatchingServerServiceServer};
// these "use" lines import the corresponding Rust structs from the generated module "service".
use matching_server::matching_service_package::{MessageType, OrderType};
use matching_server::matching_service_package::{MessageBase, SequencedMessageBase, ResponseBase, FallibleBase};
use matching_server::matching_service_package::{Heartbeat, GeneralReject, PoolDefinitionRequest, PoolDefinitionResponse, OrderNew, OrderNewAcknowledgement, OrderCancel, OrderCancelAcknowledgement, OrderElimination, FillEvent};
use matching_server::matching_service_package::{HeartbeatResponseEnvelope, PoolDefinitionResponseEnvelope, OrderNewResponseEnvelope, OrderCancelResponseEnvelope};

// #[derive(Debug, Default)] is a Rust attribute that automatically implements the Debug and Default traits for the struct that follows.
// - Debug allows the struct to be formatted using {:?}, which is useful for printing and debugging.
// - Default provides a way to create a default value for the struct (e.g., MatcherService::default()).
#[derive(Debug, Default)]
pub struct MatcherService {}

#[tonic::async_trait]
// This line starts an implementation block in Rust.
// "impl Trait for Type" means we are providing the required method implementations for the trait "Trait" for the type "Type".
// Here, "impl MatchingServerService for MatcherService" means we are implementing the gRPC service trait "MatchingServerService" (generated from the proto file) for our struct "MatcherService".
// This allows "MatcherService" to act as a gRPC server for the defined service.
impl MatchingServerService for MatcherService {
    // Even though the function's return type is defined in the proto file, tonic generates a Rust trait
    // with associated types for each streaming response. This is because, in Rust, the concrete type
    // implementing the stream (i.e., what will actually yield the response messages) must be specified
    // in the trait implementation. The proto file only describes the message types, not the actual
    // stream implementation. By requiring these type definitions, tonic allows you to choose how the
    // stream is produced (e.g., using tonic's Streaming<T>, a custom stream, etc.), providing flexibility
    // and type safety in the Rust service implementation.
    type OnHeartbeatStream = tonic::codec::Streaming<HeartbeatResponseEnvelope>;
    type OnOrderNewStream = tonic::codec::Streaming<OrderNewResponseEnvelope>;
    type OnOrderCancelStream = tonic::codec::Streaming<OrderCancelResponseEnvelope>;

    async fn on_heartbeat(
        &self,
        _request: Request<tonic::Streaming<Heartbeat>>,
    ) -> Result<Response<Self::OnHeartbeatStream>, Status> {
        unimplemented!("on_heartbeat not yet implemented")
    }

    async fn on_pool_definition_request(
        &self,
        _request: Request<PoolDefinitionRequest>,
    ) -> Result<Response<PoolDefinitionResponseEnvelope>, Status> {
        unimplemented!("on_pool_definition_request not yet implemented")
    }

    async fn on_order_new(
        &self,
        _request: Request<tonic::Streaming<OrderNew>>,
    ) -> Result<Response<Self::OnOrderNewStream>, Status> {
        unimplemented!("on_order_new not yet implemented")
    }

    async fn on_order_cancel(
        &self,
        _request: Request<tonic::Streaming<OrderCancel>>,
    ) -> Result<Response<Self::OnOrderCancelStream>, Status> {
        unimplemented!("on_order_cancel not yet implemented")
    }
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let addr = "[::1]:50051".parse()?;
    let matcher = MatcherService::default();

    println!("Matcher gRPC server listening on {}", addr);

    Server::builder()
        .add_service(MatchingServerServiceServer::new(matcher))
        .serve(addr)
        .await?;

    Ok(())
}
